# Site settings
title: Tigefa
email: tigefarb@gmail.com
description: "All out of the box application built with top of Ruby on Rails"
baseurl: ""
url: "https://tigefa.github.io"
twitter_username: tigefarb
github_username:  tigefa

# Build settings
markdown: kramdown
exclude: ["script", "vendor", "node_modules", "README.markdown", "LICENSE", "venv", "penv", "pyenv", "Gemfile", "Gemfile.lock"]
